SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/macfp32_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mk_mac_fp.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mk_mac_fp
MODULE   := test_macfp32

include $(shell cocotb-config --makefiles)/Makefile.sim
