SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/mac_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mk_mac_unit.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mk_mac_unit
MODULE   := test_mac

include $(shell cocotb-config --makefiles)/Makefile.sim
