SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/macint32_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mk_mac_int.v #\
		#$(PWD)/verilog/mk_mac_int.v \
		#$(PWD)/verilog/mk_mac_int.v \
		#$(PWD)/verilog/mk_mac_int.v
		


EXTRA_ARGS = --trace --trace-structs --timescale 1ns/1ps

TOPLEVEL = mk_mac_int
MODULE   := test_macint32

include $(shell cocotb-config --makefiles)/Makefile.sim
